apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: rabbitmq-consumer
spec:
  scaleTargetRef:
    name: rabbitmq-consumer
  pollingInterval: 1
  cooldownPeriod: 2
  maxReplicaCount: 30
  triggers:
    - type: rabbitmq
      metadata:
        host: amqp://user:PASSWORD@rabbitmq.default.svc.cluster.local:5672
        queueName: hello
        queueLength: "2"
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 2
          policies:
          - type: Pods
            value: 100
            periodSeconds: 2
        scaleUp:
          stabilizationWindowSeconds: 0
          policies:
          - type: Pods
            value: 100
            periodSeconds: 1
